// Email Agent Configuration Tokens
export const EMAIL_CLASSIFICATION_CONFIG = 'EMAIL_CLASSIFICATION_CONFIG';
export const EMAIL_SUMMARIZATION_CONFIG = 'EMAIL_SUMMARIZATION_CONFIG';
export const EMAIL_REPLY_DRAFT_CONFIG = 'EMAIL_REPLY_DRAFT_CONFIG';
export const RAG_EMAIL_TRIAGE_CONFIG = 'RAG_EMAIL_TRIAGE_CONFIG';

// Email Service Tokens
export const EMAIL_SERVICE = 'EMAIL_SERVICE';
export const EMAIL_TRIAGE_SERVICE = 'EMAIL_TRIAGE_SERVICE';
export const EMAIL_DELEGATION_SERVICE = 'EMAIL_DELEGATION_SERVICE'; 